<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ShippingAddressTableSeeder extends Seeder
{
    public function run(): void
    {
        // $addresses = [
        //     ['id' => 1, 'user_id' => 1, 'address' => '123 Street A, City B', 'created_at' => now(), 'updated_at' => now()],
        //     ['id' => 2, 'user_id' => 2, 'address' => '456 Street C, City D', 'created_at' => now(), 'updated_at' => now()],
        //     ['id' => 3, 'user_id' => 3, 'address' => '789 Street E, City F', 'created_at' => now(), 'updated_at' => now()],
        //     ['id' => 4, 'user_id' => 4, 'address' => '101 Street G, City H', 'created_at' => now(), 'updated_at' => now()],
        //     ['id' => 5, 'user_id' => 5, 'address' => '202 Street I, City J', 'created_at' => now(), 'updated_at' => now()],
        // ];
        $addresses = [
        [   
            'id' => 1,
            'user_id' => 1,
            'receiver_name' => 'John Doe',
            'receiver_phone' => '0901234561',
            'city' => 'City 1',
            'ward' => 'Ward 1',
            'district' => 'District 1',
            'address' => '123 Address 1',
            'default' => 1,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],
        [
            'id' => 2,
            'user_id' => 2,
            'receiver_name' => 'Jane Doe',
            'receiver_phone' => '0901234562',
            'city' => 'City 2',
            'ward' => 'Ward 2',
            'district' => 'District 2',
            'address' => '123 Address 2',
            'default' => null,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],
        [
            'id' => 3,
            'user_id' => 3,
            'receiver_name' => 'Alice Smith',
            'receiver_phone' => '0901234563',
            'city' => 'City 3',
            'ward' => 'Ward 3',
            'district' => 'District 3',
            'address' => '123 Address 3',
            'default' => 1,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],
        [
            'id' => 4,
           'user_id' => 4,
            'receiver_name' => 'Bob Smith',
            'receiver_phone' => '0901234564',
            'city' => 'City 4',
            'ward' => 'Ward 4',
            'district' => 'District 4',
            'address' => '123 Address 4',
            'default' => null,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],
        [
            'id' => 5,
           'user_id' => 5,
            'receiver_name' => 'Charlie Brown',
            'receiver_phone' => '0901234565',
            'city' => 'City 5',
            'ward' => 'Ward 5',
            'district' => 'District 5',
            'address' => '123 Address 5',
            'default' => 1,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],
        [
            'id' => 6,
            'user_id' => 6,
            'receiver_name' => 'David Wilson',
            'receiver_phone' => '0901234566',
            'city' => 'City 6',
            'ward' => 'Ward 6',
            'district' => 'District 6',
            'address' => '123 Address 6',
            'default' => null,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],
        [
            'id' => 7,
            'user_id' => 7,
            'receiver_name' => 'Emma Johnson',
            'receiver_phone' => '0901234567',
            'city' => 'City 7',
            'ward' => 'Ward 7',
            'district' => 'District 7',
            'address' => '123 Address 7',
            'default' => 1,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],
        [
            'id' => 8,
            'user_id' => 8,
            'receiver_name' => 'Fiona Davis',
            'receiver_phone' => '0901234568',
            'city' => 'City 8',
            'ward' => 'Ward 8',
            'district' => 'District 8',
            'address' => '123 Address 8',
            'default' => null,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],
        [
            'id' => 9,
           'user_id' => 9,
            'receiver_name' => 'George Wilson',
            'receiver_phone' => '0901234569',
            'city' => 'City 9',
            'ward' => 'Ward 9',
            'district' => 'District 9',
            'address' => '123 Address 9',
            'default' => 1,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],
        [
            'id' => 10,
            'user_id' => 10,
            'receiver_name' => 'Hannah Baker',
            'receiver_phone' => '0901234570',
            'city' => 'City 10',
            'ward' => 'Ward 10',
            'district' => 'District 10',
            'address' => '123 Address 10',
            'default' => null,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],
        [
            'id' => 11,
            'user_id' => 11,
            'receiver_name' => 'Isaac Clark',
            'receiver_phone' => '0901234571',
            'city' => 'City 11',
            'ward' => 'Ward 11',
            'district' => 'District 11',
            'address' => '123 Address 11',
            'default' => 1,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],
        [
            'id' => 12,
            'user_id' => 12,
            'receiver_name' => 'Jackie Ray',
            'receiver_phone' => '0901234572',
            'city' => 'City 12',
            'ward' => 'Ward 12',
            'district' => 'District 12',
            'address' => '123 Address 12',
            'default' => null,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],
        [
            'id' => 13,
           'user_id' => 13,
            'receiver_name' => 'Kevin Black',
            'receiver_phone' => '0901234573',
            'city' => 'City 13',
            'ward' => 'Ward 13',
            'district' => 'District 13',
            'address' => '123 Address 13',
            'default' => 1,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],
        [
            'id' => 14,
            'user_id' => 14,
            'receiver_name' => 'Laura Green',
            'receiver_phone' => '0901234574',
            'city' => 'City 14',
            'ward' => 'Ward 14',
            'district' => 'District 14',
            'address' => '123 Address 14',
            'default' => null,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],
        [
            'id' => 15,
            'user_id' => 15,
            'receiver_name' => 'Megan White',
            'receiver_phone' => '0901234575',
            'city' => 'City 15',
            'ward' => 'Ward 15',
            'district' => 'District 15',
            'address' => '123 Address 15',
            'default' => 1,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],
        [
            'id' => 16,
            'user_id' => 16,
            'receiver_name' => 'Nathan Hall',
            'receiver_phone' => '0901234576',
            'city' => 'City 16',
            'ward' => 'Ward 16',
            'district' => 'District 16',
            'address' => '123 Address 16',
            'default' => null,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],
        [
            'id' => 17,
            'user_id' => 17,
            'receiver_name' => 'Olivia Brown',
            'receiver_phone' => '0901234577',
            'city' => 'City 17',
            'ward' => 'Ward 17',
            'district' => 'District 17',
            'address' => '123 Address 17',
            'default' => 1,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],
        [
            'id' => 18,
            'user_id' => 18,
            'receiver_name' => 'Paul Gray',
            'receiver_phone' => '0901234578',
            'city' => 'City 18',
            'ward' => 'Ward 18',
            'district' => 'District 18',
            'address' => '123 Address 18',
            'default' => null,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],
        [
            'id' => 19,
            'user_id' => 19,
            'receiver_name' => 'Quincy Blue',
            'receiver_phone' => '0901234579',
            'city' => 'City 19',
            'ward' => 'Ward 19',
            'district' => 'District 19',
            'address' => '123 Address 19',
            'default' => 1,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],
        [
            'id' => 20,
            'user_id' => 20,
            'receiver_name' => 'Rachel Gold',
            'receiver_phone' => '0901234580',
            'city' => 'City 20',
            'ward' => 'Ward 20',
            'district' => 'District 20',
            'address' => '123 Address 20',
            'default' => null,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],
];  

        DB::table('shipping_addresses')->insert($addresses);
    }
}
